name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest

    env:
      GIT_COMMANDS: false

    steps:
    - uses: actions/checkout@v3

    - name: List targets
      run: make help
