name: Project Makefile
run-name: ${{ github.actor }} is Testing Project Makefile 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash
    working-directory: ./test/django-init-wagtail/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        node-version: [22.x]
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './test/django-init-wagtail/package.json'

    - name: Install Node Dependencies
    - run: make -f ../../Makefile npm-install
    - run: npm run build --if-present

    - name: Install Python Dependencies
      run: |
        make -f ../../Makefile pip-install
